### ISSUE TITLE
AttributeError: FakeDb instance has no attribute 'templates'

### ISSUE THREAD

**Issue by deepchatterjeeligo** [reedessick/lvalertTest#10]
Thrown when faking CBC_pycbc_AllSky using simulate.py

>  File "/home/deep/github_forked/lvalertMP/lvalert/interactiveQueue.py", line 190, in interactiveQueue
    parseAlert( queue, queueByGraceID, e, t0, config )
  File "/home/deep/github_forked/approval_processorMP/approval_processorMPutils.py", line 205, in parseAlert
    event_dict.update() # update the event_dict with signoffs and iDQ info
  File "/home/deep/github_forked/approval_processorMP/eventDictClassMethods.py", line 159, in update
    url = self.client.templates['signoff-list-template'].format(graceid=self.graceid) # construct url for the operator/advocate signoff list
AttributeError: FakeDb instance has no attribute 'templates'

**Comment by reedessick** [comment]
closed in favor of #11
